#!/usr/bin/env bun
/**
 * Create a business object on a MyBPM stand the way the CONSTRUCTOR does it —
 * no `.mybpm.zip` import, only `/web/v2/business-objects/*` calls.
 *
 * The call sequence (captured from the Angular client, v4.24.25.632):
 *   1. load-bo-groups                      → resolve the target BO group by name
 *   2. create-bo   {boGroupId, boCategory} → a BO named «Бизнес объект №N» is ALREADY on the stand
 *   3. save-business-object-portion        → rename (partial patch: id + nameMap + recordNameMap + description)
 *   4. generate-business-form-field        → one call per field, returns a ready field DTO with a fresh fieldId
 *   5. save-business-object-portion        → full BO DTO + editedFields/addedFieldIds/deletedFieldIds
 *   6. load-business-object-by-id          → verify
 *
 * Codes (BO code, field codes) are generated BY THE SERVER out of the names — never send them.
 *
 * Usage:
 *   bun tools/create-bo-constructor.bun.ts \
 *     --token "<LOCAL_PRIVATE_SwebToken without the JSON quotes>" \
 *     --group "Бизнес-объект" \
 *     --name  "Проба конструктора 2026-09-18" \
 *     --desc  "Пробный БО" \
 *     --field "Наименование:INPUT_TEXT" --field "Количество:INPUT_NUMBER"
 *
 *   bun tools/create-bo-constructor.bun.ts --token … --list-groups

 * A panel (`--category BO_PANEL`) is built out of NESTED OBJECTS — registry widgets:
 *     --category BO_PANEL --field "Проба UI 2026-09-18:BO@OpmGDzaQRUT27jky"
 *   (`BO@<boId>` → `generate-business-form-field {fieldType: "BO", fieldBoId: <boId>}`.)
 *
 * Field settings («Настройки поля» in the constructor) — the full field grammar is
 *     --field "Метка:TYPE[@<boId>][#вариант|вариант|…][!req,uniq,readonly,nocol]"
 *   `!req` = «Обязательное» (isRequired), `!uniq` = «Уникальное» (isUnique),
 *   `!key=value` sets ANY key of the field DTO, dotted for a nested one — `!dateOnlyPast=true`,
 *   `!textCase=UPPER`, `!maxLength=10`, `!params.url=https://…` (value parsed as JSON, else a string;
 *   no «,» inside a value). The settings and their keys: MYBPM-UI-API.md §5h.
 *   `!track` on a date field = «Отслеживать статус» with its TAB_GROUP wrapper and «Статус» dropdown (the
 *   sequence captured from the constructor 2026-09-30; this tool's version of it has not been run yet).
 *   A nested object `BO@<boId>` gets `viewType: TABLE` and the target's columns, as the constructor does.
 *   `!readonly` = «Только для чтения» (isReadonly; NEVER together with req — such a record cannot be
 *   saved), `!nocol` drops the registry column that req/uniq switch on by themselves.
 *   A «Выпадающий список» takes its options from a DICTIONARY — `DROPDOWN_SINGLE@<dictionary boId>`
 *   (optionSource FROM_BO, `options` stays empty: the stand reads the rows live) — or from a LOCAL
 *   list — `DROPDOWN_SINGLE#Новый|В работе|Готово` (optionSource FROM_FIELD, one `options` entry per
 *   variant, ids from `v2/id-loader/load-portion`).
 *   `--list-dicts` prints the dictionaries of the company with their row counts.
 *
 * Widgets and system fields are NOT `--field`s — the server has a generator of its own for each
 * (MYBPM-UI-API.md §5i):
 *     --widget "BUTTON:Кнопка:knopka:https://example.org/hook"   (TYPE:Метка[:код][:url])
 *     --widget "SIGNATURE:ЭЦП/SMS:ecp_sms"  --widget "CURRENT_USER:Текущий пользователь:cur_user"
 *     --native CREATED_AT   --native CREATED_BY   --native OPEN_COUNT
 *   A widget's code and a BUTTON's/IFRAME's url are saved by their own controllers
 *   (`v2/button`, `v2/iframe`, `v2/captcha`, `v2/signature`, `v2/current-date`,
 *   `v2/widget-current-user`) AFTER the BO is saved — they are not keys of the field DTO.
 *   Each system field and each CURRENT_* widget (and SIGNATURE) may be placed ONCE per BO.
 *
 * Token: Chrome → localStorage.LOCAL_PRIVATE_SwebToken, strip the surrounding JSON quotes;
 * pass it as a file (`--token-file`) rather than on the command line.
 * It is short-lived — read it again every session, never commit it.
 */

const argv = Bun.argv.slice(2);
const flag = (name: string): string | undefined => {
  const i = argv.indexOf(`--${name}`);
  return i >= 0 ? argv[i + 1] : undefined;
};
const flagAll = (name: string): string[] => {
  const out: string[] = [];
  argv.forEach((a, i) => { if (a === `--${name}`) out.push(argv[i + 1]); });
  return out;
};
const has = (name: string) => argv.includes(`--${name}`);

const stand = flag("stand");
if (!stand) throw new Error("--stand <host> is required: the stand host is never implied");
const tokenFile = flag("token-file");
const token = (tokenFile ? (await Bun.file(tokenFile).text()).trim() : undefined)
  ?? flag("token") ?? Bun.env.MYBPM_TOKEN;
if (!token) {
  console.error("no token: pass --token-file <path> / --token <value> or set MYBPM_TOKEN");
  process.exit(1);
}

/** `/web/v2` envelope: params first, body second (see MYBPM-UI-API.md §1). */
async function call<T = any>(method: string, params: object = {}, body: object = {}, controller = "business-objects"): Promise<T> {
  const res = await fetch(`https://${stand}/web/v2/${controller}/${method}`, {
    method: "POST",
    headers: { "Content-Type": "application/json", token: token! },
    body: JSON.stringify({
      useParamsFromBody: true,
      params_Lr1oSgwPR8: params,
      body_o1nhHUG480: body,
    }),
  });
  const text = await res.text();
  if (!text) return null as T; // some methods answer 200 with an empty body
  const json = JSON.parse(text);
  if (json && typeof json === "object" && ("errorType" in json || "className" in json)) {
    throw new Error(`${method}: ${json.errorType ?? json.className} ${json.message ?? ""} (traceId ${json.traceId ?? "-"})`);
  }
  return json as T;
}

/** save-business-object-portion chunks the JSON at 80 000 chars; each part carries the previous part's id. */
async function savePortion(payload: object): Promise<string | null> {
  const json = JSON.stringify(payload);
  const parts: string[] = [];
  for (let i = 0; i < json.length; i += 80_000) parts.push(json.slice(i, i + 80_000));
  let id: string | null = null;
  for (let i = 0; i < parts.length; i++) {
    id = await call<string>("save-business-object-portion", {}, {
      jsonPart: parts[i], orderIndex: i, isLast: i === parts.length - 1, id,
    });
  }
  return id;
}

const langMap = (v: string) => ({ KAZ: null, ENG: null, RUS: v, QAZ: null });

/**
 * The columns of a nested-object table, built the way the constructor's `createFormFieldByBoId` builds them
 * from the TARGET BO: every field listed, `toShow` = the target's own registry column flag; if the target
 * has no column at all, its first field is shown; at most 5 shown, a TAB_GROUP / PROGRESS_BAR never.
 */
async function boFieldRefsOf(refBoId: string) {
  const target = await call<any>("load-business-object-by-id", { businessObjectId: refBoId });
  const fields = [...(target.formFields ?? [])]
    .sort((a, b) => (a.gridPosition?.y ?? 0) - (b.gridPosition?.y ?? 0) || (a.gridPosition?.x ?? 0) - (b.gridPosition?.x ?? 0))
    .sort((a, b) => a.tableColOrderIndex - b.tableColOrderIndex);
  const anyColumn = fields.some(f => f.tableColToShow);
  const refs: any[] = [];
  for (const g of fields) {
    const r = { fieldId: g.fieldId, label: g.label, toShow: !!g.tableColToShow, type: g.type, checked: false,
      orderIndex: g.tableColOrderIndex, gridPosition: g.gridPosition };
    if (!anyColumn && !refs.some(x => x.toShow)) r.toShow = true;
    if (["TAB_GROUP", "PROGRESS_BAR"].includes(r.type) || refs.filter(x => x.toShow).length >= 5) r.toShow = false;
    refs.push(r);
  }
  return refs;
}

type BoGroup = { id: string; name: string; code: string | null; orderIndex: number; kind: string };
const groups = await call<BoGroup[]>("load-bo-groups");

if (has("list-groups")) {
  for (const g of groups) console.log(`${g.id}\t${g.kind}\t${g.name}`);
  process.exit(0);
}

// The dictionaries a «Выпадающий список» can be bound to, with the number of rows each one has —
// binding to an EMPTY dictionary is legal and gives an empty dropdown on the form.
if (has("list-dicts")) {
  const dicts = await call<{ id: string; name: string }[]>("load-bo-dictionary-list");
  for (const d of dicts) {
    const opts = await call<any[]>("load-dictionary-bo-field-options", { boId: d.id });
    console.log(`${d.id}\t${String(opts?.length ?? 0).padStart(4)}\t${d.name}`);
  }
  process.exit(0);
}

const groupName = flag("group");
const name = flag("name");
const desc = flag("desc") ?? "";
const category = flag("category") ?? "BO"; // BO | BO_DICTIONARY | BO_COMPOSITE | BO_PANEL | BO_PROCESS
// «Метка:TYPE» — an ordinary field; «Метка:BO@<boId>» — a NESTED object (a registry widget on a panel),
// which is the same call with the extra `fieldBoId` param; «@<boId>» on a DROPDOWN_SINGLE is the
// dictionary it reads its options from. `#a|b|c` = a local option list, `!req,uniq,…` = field settings.
// Parsed from the right, because a stand id may itself contain «@» (`kNfvHppcNSR6Wz@B`).
const fields = flagAll("field").map(s => {
  const at = s.lastIndexOf(":");
  const label = s.slice(0, at);
  let spec = s.slice(at + 1);
  let flags: string[] = [];
  const bang = spec.indexOf("!");
  if (bang >= 0) { flags = spec.slice(bang + 1).split(",").filter(Boolean); spec = spec.slice(0, bang); }
  let options: string[] = [];
  const hash = spec.indexOf("#");
  if (hash >= 0) { options = spec.slice(hash + 1).split("|").filter(Boolean); spec = spec.slice(0, hash); }
  const at2 = spec.indexOf("@");
  const type = at2 >= 0 ? spec.slice(0, at2) : spec;
  const refBoId = at2 >= 0 ? spec.slice(at2 + 1) : undefined;
  // `key=value` sets ANY key of the field DTO (`params.url=…` a nested one); the value is JSON when it
  // parses (true, 12, "UPPER", {…}), else the bare string. A value cannot contain «,» (the flag separator).
  const sets = flags.filter(f => f.includes("=")).map(parseSet);
  flags = flags.filter(f => !f.includes("="));
  const unknown = flags.filter(f => !["req", "uniq", "readonly", "nocol", "track"].includes(f));
  if (unknown.length) { console.error(`unknown field flag(s): ${unknown.join(", ")}`); process.exit(1); }
  return { label, type, refBoId, options, flags, sets };
});
function parseSet(kv: string): { path: string[]; value: unknown } {
  const eq = kv.indexOf("=");
  const raw = kv.slice(eq + 1);
  let value: unknown = raw;
  try { value = JSON.parse(raw); } catch { /* a bare string */ }
  return { path: kv.slice(0, eq).split("."), value };
}
/** `--widget "TYPE:Метка[:код][:url]"` — a widget; `--native TYPE` — a system field. */
const widgets = flagAll("widget").map(raw => {
  const parts: string[] = [];
  let rest = raw;
  for (let k = 0; k < 3 && rest.includes(":"); k++) { parts.push(rest.slice(0, rest.indexOf(":"))); rest = rest.slice(rest.indexOf(":") + 1); }
  parts.push(rest);
  const [type, label, code, url] = parts;
  if (!type || !label) { console.error(`--widget expects "TYPE:Метка[:код][:url]", got ${raw}`); process.exit(1); }
  return { type, label, code: code || undefined, url: url || undefined, fieldId: undefined as string | undefined };
});
const natives = flagAll("native");

if (!groupName || !name) {
  console.error("need --group <name|id> and --name <BO name>; --list-groups shows the groups");
  process.exit(1);
}

const group = groups.find(g => g.name === groupName || g.id === groupName);
if (!group) {
  console.error(`group not found: ${groupName}`);
  process.exit(1);
}

// 2. create — the BO exists on the stand from this moment on, under a generated name.
const created = await call<{ id: string; name: string; orderIndex: number }>(
  "create-bo", {}, { boGroupId: group.id, boCategory: category },
);
console.log(`created  ${created.id}  «${created.name}»  in «${group.name}»`);

// 3. rename — a PARTIAL patch of the BO; the server derives the BO code from the name (max 30 chars).
await savePortion({
  businessObject: {
    id: created.id,
    nameMap: langMap(name),
    recordNameMap: langMap(name),
    description: desc,
  },
});

// 4-5. fields — generate a DTO per field, then save the whole BO with the added ids.
let renamedCode: string | null = null;
if (fields.length || widgets.length || natives.length) {
  // RACE: a field save that lands within ~1 s of the rename makes the server append a 16-char uniquifier
  // to the freshly generated BO code («Test_koda_4_2026_09_18HXpmEa21vtnNLVsl»), and a BO code is never
  // regenerated afterwards. Three seconds is enough; the Angular client never hits it because a human
  // types the name and drags fields seconds apart.
  renamedCode = (await call<any>("load-business-object-by-id", { businessObjectId: created.id })).code;
  await Bun.sleep(3000);
  const bo = await call<any>("load-business-object-by-id", { businessObjectId: created.id });
  const added: any[] = [];
  const edits: any[] = [];
  for (const [i, f] of fields.entries()) {
    // `fieldBoId` is the NESTED-object target; a dropdown's dictionary is not passed here — the client
    // sets `refBoId` on the generated DTO instead (bundle: `toggleRefBoId` → `saveRefBoId`).
    const dto = await call<any>("generate-business-form-field",
      { boId: created.id, fieldType: f.type, fieldBoId: f.type === "BO" ? f.refBoId : undefined });
    dto.label = f.label;
    dto.labelMap = langMap(f.label);
    // 15 columns = full width; a plain field is 4 rows high, a nested-object table 6 (what the UI sends).
    const rows = f.type === "BO" ? 6 : 4;
    dto.gridPosition = { x: 0, y: i * 4, rows, cols: 15 };
    // Field settings. The UI writes exactly these keys and nothing else (`saveIsRequired`, `saveIsUnique`,
    // `saveIsReadonly`, `saveOptionSource`, `saveRefBoId`, `saveFormBoOptions`), each one also landing in
    // `editedFields` as a one-key patch — which is what `edit` below reproduces.
    const edit: any = { fieldId: dto.fieldId, gridPosition: dto.gridPosition, needFreezeWhenScroll: false };
    const set = (k: string, v: unknown) => { dto[k] = v; edit[k] = v; };
    if (f.flags.includes("req")) set("isRequired", true);
    if (f.flags.includes("uniq")) set("isUnique", true);
    if (f.flags.includes("readonly")) set("isReadonly", true);
    // «Обязательное» / «Уникальное» switch the registry column on by themselves (`assignTableColToShow`).
    if ((f.flags.includes("req") || f.flags.includes("uniq")) && !f.flags.includes("nocol")) {
      set("tableColToShow", true);
    }
    // `!key=value` overrides — a nested path replaces the whole top-level object in the patch, the way
    // the client's own `saveParams` does.
    for (const { path, value } of f.sets) {
      if (path.length === 1) { set(path[0], value); continue; }
      const top = structuredClone(dto[path[0]] ?? {});
      let o: any = top;
      for (const k of path.slice(1, -1)) o = o[k] ??= {};
      o[path.at(-1)!] = value;
      set(path[0], top);
    }
    // A nested object: what the constructor adds on drop (`createFormFieldByBoId`) — without `viewType`
    // the card renders an empty box, without `boFieldRefs` a table with no columns.
    if (f.type === "BO" && f.refBoId) {
      set("refBoId", f.refBoId);
      set("viewType", "TABLE");
      set("boFieldRefs", await boFieldRefsOf(f.refBoId));
    }
    if (f.type === "DROPDOWN_SINGLE" && f.refBoId) {
      set("optionSource", "FROM_BO");
      set("refBoId", f.refBoId);
      set("options", []); // the rows are read from the dictionary live, never stored on the field
    }
    if (f.type === "DROPDOWN_SINGLE" && f.options.length) {
      const ids = await call<string[]>("load-portion", {}, {}, "id-loader");
      set("optionSource", "FROM_FIELD");
      set("refBoId", null);
      set("options", f.options.map((label, j) => ({
        instanceId: null, id: ids[j], label, color: null, code: null,
        orderIndex: j, hiddenInKanban: false, labelMap: langMap(label),
      })));
    }
    added.push(dto);
    edits.push(edit);
    // «Отслеживать статус» (`saveNeedTrackStatus`): the flag alone does nothing — the constructor also adds
    // a TAB_GROUP wrapper and a «Статус» dropdown whose option ids are PLANNED/OVERDUE/DONE/CANCELED, and
    // moves the date into the wrapper's tab (MYBPM-UI-API.md §5h «Six more gear flags»).
    if (f.flags.includes("track")) {
      const wrap = await call<any>("generate-business-form-field", { boId: created.id, fieldType: "TAB_GROUP" });
      const tabId = (await call<string[]>("load-portion", {}, {}, "id-loader"))[0];
      Object.assign(wrap, {
        trackedFieldId: dto.fieldId, tabId: dto.tabId ?? null, gridPosition: { ...dto.gridPosition, cols: 15, rows: 4 },
        tabs: [{ id: tabId, label: "Статус объекта", isActive: true, chosenAccessRight: false, orderIndex: 0,
          isInvalid: false, isRight: false, isDefault: false, labelMap: { RUS: "Статус объекта" } }],
      });
      const status = await call<any>("generate-business-form-field", { boId: created.id, fieldType: "DROPDOWN_SINGLE" });
      const options = ([["PLANNED", "Запланировано", "#0048ff"], ["OVERDUE", "Просрочено", "#d3a52f"],
        ["DONE", "Выполнено", "#6797fa"], ["CANCELED", "Отменено", "#6797fa"]] as const)
        .map(([id, label, color]) => ({ id, checked: false, label, color, orderIndex: 0, labelMap: { RUS: label } }));
      Object.assign(status, {
        label: "Статус", labelMap: langMap("Статус"), trackedFieldId: dto.fieldId, tabId,
        gridPosition: { cols: 6, rows: 3, x: 9, y: 0 }, optionSource: "FROM_FIELD", options,
      });
      set("needTrackStatus", true);
      set("tabId", tabId);
      set("gridPosition", { cols: 9, rows: 3, x: 0, y: 0 });
      added.push(wrap, status);
      edits.push({ fieldId: status.fieldId, options });
    }
  }
  // Widgets and system fields ride along in the same save — only their generator differs.
  let y = fields.length * 4;
  for (const w of widgets) {
    const dto = await call<any>("generate-business-form-widget", { widgetType: w.type });
    dto.label = w.label;
    dto.labelMap = langMap(w.label);
    const rows = ["SIGNATURE", "CAPTCHA", "CURRENT_USER"].includes(w.type) ? 6 : w.type === "IFRAME" ? 8 : 4;
    dto.gridPosition = { x: 0, y, cols: 15, rows };
    y += rows;
    added.push(dto);
    edits.push({ fieldId: dto.fieldId, gridPosition: dto.gridPosition, needFreezeWhenScroll: false });
    w.fieldId = dto.fieldId;
  }
  for (const t of natives) {
    const dto = await call<any>("generate-business-form-field-by-native", { nativeType: t });
    if (!dto) { console.log(`native    ${t} — the server has no generator for it (PARTICIPANTS is the known one)`); continue; }
    // label and labelMap come filled in all four languages; only the layout is ours
    const rows = dto.type === "BO" ? 6 : 4;
    dto.gridPosition = { x: 0, y, cols: 15, rows };
    y += rows;
    added.push(dto);
    edits.push({ fieldId: dto.fieldId, gridPosition: dto.gridPosition, needFreezeWhenScroll: false });
  }
  bo.formFields = [...(bo.formFields ?? []), ...added];
  await savePortion({
    businessObject: bo,
    editedFields: edits,
    addedFieldIds: added.map(f => f.fieldId),
    deletedFieldIds: [],
  });
  // `useAsKeyInMigration` is DROPPED on a field that is being added (every other key survives) — it takes
  // a second, one-key patch on the now existing field (MYBPM-UI-API.md §5h «Поведение» and «Интеграция»).
  const keyFields = added.filter(f => f.useAsKeyInMigration);
  if (keyFields.length) {
    const saved = await call<any>("load-business-object-by-id", { businessObjectId: created.id });
    for (const f of saved.formFields) if (keyFields.some(k => k.fieldId === f.fieldId)) f.useAsKeyInMigration = true;
    await savePortion({
      businessObject: saved,
      editedFields: keyFields.map(f => ({ fieldId: f.fieldId, useAsKeyInMigration: true })),
      addedFieldIds: [],
      deletedFieldIds: [],
    });
  }
}

// 6a. A widget's code and url live in the widget's own controller, not in the BO DTO — set them after
// the save, or the archive comes out with a code the server derived from the label.
const WIDGET_CODE_CALL: Record<string, { controller: string; method: string; idKey: string }> = {
  SIGNATURE: { controller: "signature", method: "save-signature-code", idKey: "signatureId" },
  BUTTON: { controller: "button", method: "save-button-code", idKey: "buttonId" },
  IFRAME: { controller: "iframe", method: "save-iframe-code", idKey: "iframeId" },
  CAPTCHA: { controller: "captcha", method: "save-captcha-code", idKey: "captchaId" },
  CURRENT_DATE: { controller: "current-date", method: "save-current-date-code", idKey: "currentDateId" },
  CURRENT_DAY: { controller: "current-date", method: "save-current-date-code", idKey: "currentDateId" },
  CURRENT_MONTH: { controller: "current-date", method: "save-current-date-code", idKey: "currentDateId" },
  CURRENT_DAY_AND_MONTH: { controller: "current-date", method: "save-current-date-code", idKey: "currentDateId" },
  CURRENT_YEAR: { controller: "current-date", method: "save-current-date-code", idKey: "currentDateId" },
  CURRENT_USER: { controller: "widget-current-user", method: "save-current-user-code", idKey: "currentUserId" },
};
for (const w of widgets as any[]) {
  if (!w.fieldId) continue;
  const c = WIDGET_CODE_CALL[w.type];
  if (!c) { console.error(`unknown --widget type ${w.type}`); continue; }
  // These methods take everything in the PARAMS half of the envelope; a body-only call silently does nothing.
  if (w.code) await call(c.method, { boId: created.id, [c.idKey]: w.fieldId, code: w.code }, {}, c.controller);
  if (w.url && (w.type === "BUTTON" || w.type === "IFRAME")) {
    await call(w.type === "BUTTON" ? "save-button-url" : "save-iframe-url",
      { boId: created.id, [w.type === "BUTTON" ? "buttonId" : "iframeId"]: w.fieldId, url: w.url },
      {}, w.type === "BUTTON" ? "button" : "iframe");
  }
}

// 6. verify — read the BO back the way the constructor does.
const after = await call<any>("load-business-object-by-id", { businessObjectId: created.id });
console.log(`name     «${after.name}»`);
console.log(`code      ${after.code}`);
if (renamedCode && after.code !== renamedCode) {
  console.log(`WARNING   the code changed after the field save («${renamedCode}» → «${after.code}») — the rename race`);
}
for (const f of after.formFields ?? []) {
  if (f.boFieldArchetype !== "DYNAMIC") {
    console.log(`${f.boFieldArchetype === "WIDGET" ? "widget   " : "native   "} ${f.label} / ${f.code ?? "—"} / ${f.widgetType ?? f.nativeFieldType}`);
    continue;
  }
  const settings = [
    f.isRequired ? "обязательное" : null,
    f.isUnique ? "уникальное" : null,
    f.isReadonly ? "только чтение" : null,
    f.optionSource === "FROM_BO" ? `справочник ${f.refBoId}` : null,
    f.optionSource === "FROM_FIELD" && f.options?.length ? `список: ${f.options.map((o: any) => o.label).join("|")}` : null,
  ].filter(Boolean);
  console.log(`field     ${f.label} / ${f.code} / ${f.type}${settings.length ? "  [" + settings.join(", ") + "]" : ""}`);
}
console.log(`url       https://${stand}/business-objects/editing/${after.id}/object-editing`);
